# Generated by Django 3.0.1 on 2019-12-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IotItem',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.BooleanField(default=True)),
            ],
        ),
    ]
