# Generated by Django 3.0.1 on 2019-12-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotitem',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
